# use Travis container build infrastructure
sudo: false
addons:
  postgresql: "9.4"
language:
  - python
python:
  - '2.7'
install:
  - gem install compass
  - pip install -U pip wheel
  - pip install coveralls pyramid_redis_sessions
  - npm install
  - make
before_script:
  - psql -c 'create database htest;' -U postgres
script:
  # Run all tests, with coverage if possible
  - make cover
  # Test building browser extensions
  - hypothesis-buildext conf/testext.ini chrome --base http://localhost
  - hypothesis-buildext conf/testext.ini firefox --base http://localhost
  - "hypothesis-buildext conf/production.ini chrome
    --base https://hypothes.is
    --assets chrome-extension://notarealkey/public"
  - "hypothesis-buildext conf/production.ini firefox
    --base https://hypothes.is
    --assets resource://notarealkey/hypothesis/data"
after_success:
  - coveralls
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
notifications:
  irc:
    channels:
       "chat.freenode.net#hypothes.is"
    on_success: "change"
    on_failure: "always"
